# Generated by Django 3.2.5 on 2021-07-18 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^0[0-9]{2,}[0-9]{7,}$')]),
        ),
    ]
